### ISSUE TITLE
[FEATURE REQUEST] Seperate backend from frontend

### ISSUE THREAD

**Issue by siewert87** [mickgeek/symfony-react-restful-boilerplate#1]
Hey,

thank you very much for this. Would it be make more sense to seperate the api from the spa, for example create an repository for the symfony project and an repository for the react-app?

Best,
Christian

**Comment by mickgeek** [comment]
Hi, Christian!

Thanks for your idea. But I think that the separation of applications into different repositories is useful for complex projects. This boilerplate is suitable for any type, including simple level projects.

**Comment by siewert87** [comment]
Hey Oleg,

hm...yeah, from that point of view, you are right. Thanks again for this project.

Best,
Christian
