### ISSUE TITLE
How to run api server

### ISSUE THREAD

**Issue by pegasus1982** [mickgeek/symfony-react-restful-boilerplate#13]
I followed the instruction.
I installed composer and npm modules.
I tried to run api server by using this command
`php bin/console server:run`
But it didn't run.

How can I run it?

**Comment by mickgeek** [comment]
This boilerplate has not been tested on PHP's built-in web server. You can configure it using Nginx or Apache.

[Nginx Configuration](https://github.com/mickgeek/symfony-react-restful-boilerplate/blob/master/vhosts/nginx.conf)
