### ISSUE TITLE
Cant login with initially created superuser

### ISSUE THREAD

**Issue by leventdeniz** [mickgeek/symfony-react-restful-boilerplate#18]
Steps I took:

* I set up everything according to the README
* Did not use your nginx config but set api AND frontend URLs to localhost
* I created a superuser with the symfony console command
* Tried to login
* There was no jwt token so my request threw an symfony error

I also do not understand how it is possoble to be authenticated as Superuser at this IF-Statement:
https://github.com/mickgeek/symfony-react-restful-boilerplate/blob/1d128b07774f4261099dddd9f99b031dfc50ac0c/api/src/Controller/UserController.php#L125
when it only accesses the method when you are not authenticated here:
https://github.com/mickgeek/symfony-react-restful-boilerplate/blob/1d128b07774f4261099dddd9f99b031dfc50ac0c/api/src/Controller/UserController.php#L116

**Comment by mickgeek** [comment]
Hi Levent.

What is it about the error? You should generate keys for JWT according to the instruction. It is easy. And read [the security information](https://symfony.com/doc/4.0/security.html#checking-to-see-if-a-user-is-logged-in-is-authenticated-fully) about `IS_AUTHENTICATED_ANONYMOUSLY`.

**Comment by mickgeek** [comment]
You can also follow the steps on [that message](https://github.com/mickgeek/symfony-react-restful-boilerplate/issues/3#issuecomment-532435994).

**Comment by leventdeniz** [comment]
Thank you for your replies. I think I'll have to read a bit more into symfony authentication and jwt. The issue was propably caused by a wrong configuration of me.
