### ISSUE TITLE
Bugfix

### ISSUE THREAD

**Issue by waldifubu** [mickgeek/symfony-react-restful-boilerplate#2]
Hello. This little nice project seems to work correctly.

BUT:

In file "UserTokenConttroller.php", line ca. 191:
change method from: 
$user->updateErrorCode(User::STATUS_ACTIVE);

to:
$user->setStatus(User::STATUS_ACTIVE);

I already fusioned spa into api part, so I can't set pull request. Please fix it manually.

It seems this is a good base for me.

**Comment by mickgeek** [comment]
Thanks you! Fixed.

https://github.com/mickgeek/symfony-react-restful-boilerplate/commit/d3f8433ac3d571e4702ec9aa142d3e6fc0937d6b
