### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by huiman** [mickgeek/symfony-react-restful-boilerplate#3]
Thank you for your good work, I am still novice of react.
please help me. after set up project.
I do not understand why after click login, their are no respond[redirect to successful link].

![Screen Shot 2562-09-09 at 13 12 01](https://user-images.githubusercontent.com/3445884/64507400-de096b80-d304-11e9-8a48-90c4c86f4d26.png)

and after go to http://0.0.0.0:3000/#/admin, this show 

Error

Authorization is needed.

Thank you

**Comment by mickgeek** [comment]
Hello and thank you!

Do you have any errors in your console?

Try follow these steps:
1. Change URLs in the `spa/src/constants/callConstants.js` file on your own way, if you haven't done it yet.
2. Change the `CORS_ALLOW_ORIGIN` parameter from your `api/.env` file on `^https?://(localhost|192\.168\.33\.10|restfulboilerplate\.local):?[0-9]*$`.
3. Your `hosts` file should contain the mapping like `192.168.33.10 restfulboilerplate.local api.restfulboilerplate.local`.

`192.168.33.10` - the virtual IP of my local machine. If you don't use the host names, experimenting with IP addresses.
